/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FristenRouteImport } from './routes/fristen'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as TermineRouteImport } from './routes/termine'
import { Route as UebersichtRouteImport } from './routes/uebersicht'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FristenRoute = FristenRouteImport.update({
  id: '/fristen',
  path: '/fristen',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const TermineRoute = TermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => rootRouteImport,
} as any)
const UebersichtRoute = UebersichtRouteImport.update({
  id: '/uebersicht',
  path: '/uebersicht',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/chat': typeof ChatRoute
  '/fristen': typeof FristenRoute
  '/partner': typeof PartnerRoute
  '/termine': typeof TermineRoute
  '/uebersicht': typeof UebersichtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/chat': typeof ChatRoute
  '/fristen': typeof FristenRoute
  '/partner': typeof PartnerRoute
  '/termine': typeof TermineRoute
  '/uebersicht': typeof UebersichtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/chat': typeof ChatRoute
  '/fristen': typeof FristenRoute
  '/partner': typeof PartnerRoute
  '/termine': typeof TermineRoute
  '/uebersicht': typeof UebersichtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/chat'
    | '/fristen'
    | '/partner'
    | '/termine'
    | '/uebersicht'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/chat'
    | '/fristen'
    | '/partner'
    | '/termine'
    | '/uebersicht'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/chat'
    | '/fristen'
    | '/partner'
    | '/termine'
    | '/uebersicht'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  ChatRoute: typeof ChatRoute
  FristenRoute: typeof FristenRoute
  PartnerRoute: typeof PartnerRoute
  TermineRoute: typeof TermineRoute
  UebersichtRoute: typeof UebersichtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fristen': {
      id: '/fristen'
      path: '/fristen'
      fullPath: '/fristen'
      preLoaderRoute: typeof FristenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termine': {
      id: '/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof TermineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uebersicht': {
      id: '/uebersicht'
      path: '/uebersicht'
      fullPath: '/uebersicht'
      preLoaderRoute: typeof UebersichtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  ChatRoute: ChatRoute,
  FristenRoute: FristenRoute,
  PartnerRoute: PartnerRoute,
  TermineRoute: TermineRoute,
  UebersichtRoute: UebersichtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
