/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ExportRouteImport } from './routes/export'
import { Route as FristenRouteImport } from './routes/fristen'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as WochenberichtRouteImport } from './routes/wochenbericht'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBerichteRouteImport } from './routes/_authenticated/berichte'
import { Route as AuthenticatedBoardsRouteImport } from './routes/_authenticated/boards'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedTermineRouteImport } from './routes/_authenticated/termine'
import { Route as AuthenticatedUebersichtRouteImport } from './routes/_authenticated/uebersicht'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const FristenRoute = FristenRouteImport.update({
  id: '/fristen',
  path: '/fristen',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const WochenberichtRoute = WochenberichtRouteImport.update({
  id: '/wochenbericht',
  path: '/wochenbericht',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerichteRoute = AuthenticatedBerichteRouteImport.update({
  id: '/berichte',
  path: '/berichte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardsRoute = AuthenticatedBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermineRoute = AuthenticatedTermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUebersichtRoute = AuthenticatedUebersichtRouteImport.update({
  id: '/uebersicht',
  path: '/uebersicht',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/export': typeof ExportRoute
  '/fristen': typeof FristenRoute
  '/partner': typeof PartnerRoute
  '/wochenbericht': typeof WochenberichtRoute
  '/berichte': typeof AuthenticatedBerichteRoute
  '/boards': typeof AuthenticatedBoardsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/termine': typeof AuthenticatedTermineRoute
  '/uebersicht': typeof AuthenticatedUebersichtRoute
}
export interface FileRoutesByTo {
  '/export': typeof ExportRoute
  '/fristen': typeof FristenRoute
  '/partner': typeof PartnerRoute
  '/wochenbericht': typeof WochenberichtRoute
  '/berichte': typeof AuthenticatedBerichteRoute
  '/boards': typeof AuthenticatedBoardsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/termine': typeof AuthenticatedTermineRoute
  '/uebersicht': typeof AuthenticatedUebersichtRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/export': typeof ExportRoute
  '/fristen': typeof FristenRoute
  '/partner': typeof PartnerRoute
  '/wochenbericht': typeof WochenberichtRoute
  '/_authenticated/berichte': typeof AuthenticatedBerichteRoute
  '/_authenticated/boards': typeof AuthenticatedBoardsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/termine': typeof AuthenticatedTermineRoute
  '/_authenticated/uebersicht': typeof AuthenticatedUebersichtRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/fristen'
    | '/partner'
    | '/wochenbericht'
    | '/berichte'
    | '/boards'
    | '/chat'
    | '/termine'
    | '/uebersicht'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/export'
    | '/fristen'
    | '/partner'
    | '/wochenbericht'
    | '/berichte'
    | '/boards'
    | '/chat'
    | '/termine'
    | '/uebersicht'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/export'
    | '/fristen'
    | '/partner'
    | '/wochenbericht'
    | '/_authenticated/berichte'
    | '/_authenticated/boards'
    | '/_authenticated/chat'
    | '/_authenticated/termine'
    | '/_authenticated/uebersicht'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ExportRoute: typeof ExportRoute
  FristenRoute: typeof FristenRoute
  PartnerRoute: typeof PartnerRoute
  WochenberichtRoute: typeof WochenberichtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fristen': {
      id: '/fristen'
      path: '/fristen'
      fullPath: '/fristen'
      preLoaderRoute: typeof FristenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wochenbericht': {
      id: '/wochenbericht'
      path: '/wochenbericht'
      fullPath: '/wochenbericht'
      preLoaderRoute: typeof WochenberichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/berichte': {
      id: '/_authenticated/berichte'
      path: '/berichte'
      fullPath: '/berichte'
      preLoaderRoute: typeof AuthenticatedBerichteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards': {
      id: '/_authenticated/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AuthenticatedBoardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/termine': {
      id: '/_authenticated/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof AuthenticatedTermineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uebersicht': {
      id: '/_authenticated/uebersicht'
      path: '/uebersicht'
      fullPath: '/uebersicht'
      preLoaderRoute: typeof AuthenticatedUebersichtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBerichteRoute: typeof AuthenticatedBerichteRoute
  AuthenticatedBoardsRoute: typeof AuthenticatedBoardsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedTermineRoute: typeof AuthenticatedTermineRoute
  AuthenticatedUebersichtRoute: typeof AuthenticatedUebersichtRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBerichteRoute: AuthenticatedBerichteRoute,
  AuthenticatedBoardsRoute: AuthenticatedBoardsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedTermineRoute: AuthenticatedTermineRoute,
  AuthenticatedUebersichtRoute: AuthenticatedUebersichtRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ExportRoute: ExportRoute,
  FristenRoute: FristenRoute,
  PartnerRoute: PartnerRoute,
  WochenberichtRoute: WochenberichtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
